version: '3.8'

services:
  servicios:
    build: ./servicios
    ports:
      - "8081:8080"   # Puerto externo 8081 → interno 8080
    container_name: servicios

  promociones:
    build: ./promociones
    ports:
      - "8082:8080"   # Puerto externo 8082 → interno 8080
    container_name: promociones
